### ISSUE TITLE
TE-2: Admin User Module

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#2]
Points: 13
Estimated Time: 5 days
Actual Time: -
- [x]  Setup Basic Create
- Including building form, validation, store to database, email notification, auto-activation or activation via email
- [x]  Setup Basic Update
- Including validation and storing to database
- [x]  Setup Basic Retrieve
- Including building the list of users
- [x]  Setup Basic Delete
- Including user deactivation and restore
- [x]  Listing Pagination
- Building pagination of the user list
- [x]  Listing Filters
- Create filters using search by ( Name )
- [x]  Listing Sorting
- Make sorting using ( Name ) and ( Creation Date )

---

**User Fields:**
- **Required:**
  - ID
  - First Name (Given)
  - Last Name (Surname)
  - Address Line 1
  - City
  - Country
  - State/Province
  - Zip/Postal Code
  - Primary Phone
  - E-Mail Address
  - Confirm E-Mail Address
  - Password
  - Confirm Password
  - Reminder Question
  - Reminder Answer
  - Confirm Answer
  - Do you agree with the Privacy Notice?
  - DOB
  - POB
- **Optional:**
  - Middle Initial
  - Language
  - Address Line 2
  - Company Name
  - First Name (in non-English character language)
  - Last Name (in non-English character language)
  - Address Line 1 (in non-English character language)
  - Address Line 2 (in non-English character language)
  - Address Line 3 (in non-English character language)
  - City (in non-English character language)
  - State/Province (in non-English character language)
  - Country (in non-English character language)
  - Postal Code (in non-English character language)
  - Secondary Phone
  - Fax Number

**Comment by ahmedReda1** [comment]
i need to know exactly which field you want the app to list in user admin index and  are we going to have a profile page or not ? , thanks

**Comment by babanesma** [comment]
@ahmedReda1 

- [ ] add show details page for admin users module and place it the listing page 
- [ ] move the sorting links to the table header 
- [ ] move the search bar to panel header beside the create new user button and adjust it to the right

**Comment by ahmedelbougha** [comment]
Upon planning session, the unit and behavior tests are 40% done and verification link is about to finish.

**Comment by ahmedelbougha** [comment]
Tasks to be done:

- [ ] Unit tests
- [ ] Behavior tests
- [ ] Email verification link

**Comment by ahmedelbougha** [comment]
QA Issues:

- [ ] Move the pager from top to bottom of the page
- [ ] Change the first and last names of the users to English instead of Arabic

**Comment by ahmedReda1** [comment]
points 1 ,2 are already merged to master earlier before the demo by adham 
point 3 is fixed in "User_Fixes" branch

**Comment by babanesma** [comment]
Emails issues are fixed on dev server , they are trapped on mailtrap.io ( ask for mailtrap account details )

**Comment by ahmedelbougha** [comment]
QA Issues:

**High**
- [x] When editing user, I need to select _I agree to license agreement!_ again

**Minor**
- [x] Long names need to be limited or to be broken using CSS word wrap so we can save the listing page from distortion 
- [x] Some countries don't have cities like _Niue_ and _Norfolk Island_

**Comment by ahmedelbougha** [comment]
All the issues above were not resolved!

**Comment by ahmedelbougha** [comment]
Issue not resolved:
- [ ] When editing user, I need to select I agree to license agreement! again - this should be removed completely from editing form
- [ ] Some countries don't have cities like Niue and Norfolk Island - either remove those countries or make the city not required in that case

**Comment by ahmedelbougha** [comment]
moving this to **_Done_** with one know issues in EPIC #112 (2 and 3)
