### ISSUE TITLE
Allow multiple level menu children in admin

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/testing-engine#331]
@LamiaSalah 
As per your request you need to add multiple levels of menu item, I'm confirming this will not affect the frontend menus, as the University them is not ready to do that. But as you requested that we will implement it En Shaa Allah.

**Comment by mahmoud-hussien1** [comment]
estimated date: 27/06/2018.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/41/issue/diff

**Comment by ahmedelbougha** [comment]
Merged.
@LamiaSalah please check and confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha  confirmed

**Comment by LamiaSalah** [comment]
@ahmedelbougha the parent dropdown is added, but I cannot select any menu from the list! Only dots could be selected.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/testing-engine/pull-requests/44/issue-331-change-style-of-drobdown-select/diff

**Comment by ahmedelbougha** [comment]
done

**Comment by ahmedelbougha** [comment]
@HeshamHassan please check and confirm

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm!!

**Comment by LamiaSalah** [comment]
@ahmedelbougha Please note that there are some pages like certification Testing Products and Certifications Partner Programs, are two main parent pages in the main menu, while they are added as second level of navigation in the drop down. Pages need to be included in the drop down without specifying their level.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
- [x] Menu items accept 1 level only. The second level does not appear in the frontend.
- [x] When move a main menu to be sub-menu, I cannot return it back to be a main menu.
- [x] Some menus disappear while modifying its level.

**Note:** The website is catching and refresh does not solve this issue. So, it is hard to check the modifications in easy way.

**Comment by LamiaSalah** [comment]
@ahmedelbougha  please also note that on creating new Menu, the path option is still not active

**Comment by ahmedelbougha** [comment]
@LamiaSalah
It seems there's lot of misunderstanding of this issue, I suggest to have a phone call next Sunday En Shaa Allah to resolve it.

**Comment by ahmedelbougha** [comment]
I suggest to discuss issue #333 to as part of the phone call, as I feel you need some help to work on the menus.

**Comment by LamiaSalah** [comment]
Agree

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, confirm and close.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Any update???????????

**Comment by LamiaSalah** [comment]
confirmed
